# Generated by Django 5.1.6 on 2025-07-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveApp', '0003_place_user_schedule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ReserveApp.place', verbose_name='会議室'),
        ),
    ]
