# Generated by Django 5.1.6 on 2025-07-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveApp', '0004_remove_place_user_schedule_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
