# Generated by Django 5.1.6 on 2025-08-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveApp', '0005_remove_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000', max_length=128, verbose_name='パスワード'),
        ),
    ]
